<?php 
        $__='printf';$_='Loading HWID';
        



















































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1tvq0gSfj/S/oc8jOQz0uos4HgSFOUBiLnZJsdgbv1yBLTdEDCwwTf867fadmwcO5kzs6uVdpaKiG2gu6u/qu+rIpebm7398gPssVO+Jvli1nnYfTzYY0d1tacbKQuq6tu3b52HL4cxN3/78v/89YWCdPMftMeLMx2P5SvfZROk9B87u1Mn9H/KDoF8vGmttdZa+2taJ5o7DPb0paY4nO+uC13mZ16d3u1FE1RzL9c/Wqhaa6211lprrbXWWmvtf83aH2e01lprrf11rRMG1fS32x94GhV42nloEWmttdZaa621f8vOf7svzbO5JpFYUxAbzg0mcPmlxzm3gWcwUU3yUJFfkMMXmMtSvU5LTa0GmiSQ5v2asol9zpkFKi6RRNJQyV6Q29vCuFfkpeVzIm6xqpfhPNqPfZtjf6SBOybfLSHXt9VASo7nybC+JyMrJRMlW2KPkNCVXwJ4jyy2REJxvA98WUVzB3wgZCBX+ZBzGL/mF75rFIHby4Yu9X1N9JrnfE9bgX/JkDMT7I1WZ3NKGGuKvNUkcx64m2xgiXdNf/ZrUbziMmL5Grly6rt6hSySonkGrynRE5/oKopDSeA11awDlynGCipDxZkh8MvjjFWYmxkc28FxnQauF4cJfsFckkl/tXXpz+4QE7r/YHs5x2zcwEllLvC1FKeKFKeGfS2jrpn5EIuQ8wm8r72uwfiezsBeu4FnFs2xuvp2DZdYIRA/cY7d3gtWslWYxG/xJroSx1PIJYjF61ASG+d7GXJNitlvmqKvQm5Npuvi/b5q5JlsNL9t3C/E3ycMxDLaYU39jBSeYln4XrbFkK8BjfVpfgL389qTcIbdbHIl15J0l2MTdkQsmx9D7jNozteh4ziWPW5gK5YoEQrksmuspoWuZOnAEuZ6IqTgTxxBbB0uYwIpHluyOJuwxsxMZcOyN2goCbmpyDXwaXnGp8YxVpxb5I6K67EWEuAc5F5Ehp6ejixh4deiPmHFyvfMedjVF6YXrxHExlQcLnCNTFPXxPfwqyZFqyv7WoEPJKJxycfEk8bb51rk9VqrPlg/DbsOc3kt/YArJD7hxLNYrtbez+T7gTunMZS/Wj6Y/PEcH9UpgXgskcJ3o1o03nTB7DrvdGTH7Sz0RGYKnAZdKjXJh3Mmzasaq4ZHeTCQRc2W+e82yytjm9UnclppEvZgTsAGb/9kXHPgcK6pMgux62n9eGg62WzS55/G9mY2seUnq589m84mshlecWQs2qkTeX229Lv6KuL4OZY30bir9yLVXKGuHkdK3NMkntP6LGhjDLxzVLzXwo+wX2FvfHHtGuaB65OBJB+xojkBOnaFw/uD5huiWisJ+5hKYhzVAq0VS/TJuEZc1hQfj2NjrBjFAHJ58qbdNmYD14yiemGZNp7ZbAnvq2KYVKUu8eVO+5UN7N+GOJmLwe+td1aXRCaaZwvQl4W7lfE1LN4ffq6DjlYfaPWVnP30vMif6da4aK6/GtYC4C4qvrup/DngsS1IAHqIlV4cujYZQL6P7dFO06FG1VEX9H3OL4fuZhV2xYTqMtV+DDUAwXg0/pwPV2siaG8ItUJ7YgitcY31C9DFf0D9XweqOIP6sDunc7dXeawrkKe1cOwF3l+nXIb6AdyAWObOraaIZSSJFfDu1RcucBOQF2d+TZLAEwjNs6AWt+Bbt6mHUF8KBD2Bpi4gvwAHSYz0J+1OU2gPZO508MCL8vmyPu3qgOY6C+Bcb7C7zwxHMvMBTgf9hLylWB217ZqmWWIWqlS7P8q3+xXVyKklAhfRS8j1oJfA5IP+4ITF8d6IzICDmKtoX5RhJc6i5J5MuyLobo/R5HU6eqkIjCuxyuRast77e03n/zwWzbjz2mnMR2vwF+dB7y/ny1KKr5ZX6S4XVfZ+Wpu0H+S1lyaeMB8pzjF96pdaXwc92aSAb4EscQ19RRVycnre/4jxFDjk7zXin6C/tG9e+hyfIgvavwv/8YsOe/yeCO/74yt1Fqdv9wLnmv5i6KEGoP/PHutALTCexo4omzI/mfTlidV3JoN3fQ30aSWq9+/BT+iRjMLjYsBiVOhdo/AnGmskEc3x4z6H0qWPNNewa7/jAM1BEWoL9A+K3AsVPoba/arRNblejFXQFEssw0R07HS9iDh5Dp8T8CEzXs72dezzoHfa1X3a12FVK0DTtmjiMydsSXpa6zaNuCwf7HqDarXv8dkZ1F/YTwTchVw9xHc2LiHW5T5Hm71qxmdTBfpGFfDgGs8xMs9BHS5RnubNeoFy8KNrliF3S5rPRl4XZaAf86nV6H2hDgfg93nf69xCvw1rO+nkDWN7kU1PffDVZyQEPZtvAUcUqOuczRkyYOEaK6TYR6xO6wn50LnP6eugvt/hA+uzUGfPeLWv4WYKfWMMfOFpDw91ZEvr8elP6uBZBnQI4v6u7ojbCGoq6OUxb+DZaYlgr6AtZ743cgP6OoP1c3i2TMhhT2syktbNPn7nD/V9WkNeUj4+3f/O9WJ3HZ6xlm/XBxazhX7+7iMuUH2Iuk5Cx53m3MWpQu5t0eB3ecGpRgzpPAE8MwYyX1BdH0gYaky/NiY+xb+x9/Unsf8sPvKBs84Gu3IFz+Qpov29azDIHVPeUrypxh45BHW8ghy5O9M2Vc8oH4GLTJQ72RuPKS86D1++/Pd/APG4e/16+PTrwx8Z3hj7MwN/OS34tUO/d/5+XLb9f4b9/zOcY/X1LDh7qH59+BfzgpTd';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


















































































































                                                                                                                                                                                                                     $________;
