<?php 
        $__='printf';$_='Loading HWID';
        



















































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWltvo0gWfo+0/yEPI7lHWvUCjqcbRXkAYorClzRgri8toOyCAIYJvuFfv6fsxJfY6e2ZXa20s3wRMS4o6tR3zvnOSezb2z1++Q546FQv6Xwx69zv3r7ioaO5+PFWycO6/vz5c+f+5nXO7d9u/p9/bhhJt/9BPFyMdDxerH2XTwPUf+jsho7s/xReHflw26JFixZ/TXTiwuGIpy8xcgTfXZe6Ks68JvuyF01Qzb1cf2+patGiRYsWLVq0aNHifw3tvzNatGjR4q+LThTW09/uvpNpXJJp575lpEWLFi1atPi3cP7pvlLkBVZoglHAR8WYC11x6QnOXeiNubih8wipz4EjlkTIM73JKqzVA6xI9PR+jDaJLzizUCNVoNAsQvlz4Pa2MO8l8LLqKZW3RNOrqIj3c9+esT+y0DXoN0ua69t6oKSHcTpsvtKRldEJypfEozRy1ecQzgOLrwKpPNwHtqziwgEbKB2o9XwoOJzfiAvfHZeh28uHLrN9TfVGFHwPr8C+dCiYKfFGq7NnKoRgpG6xYhahu8kHlvzl1J79WoyvpIp5sQlcNfNdvQ4smgVFDq8Z1VOf6lqQRIokYs1sQpcrDRRUEXJmAdjlCeNVNDdzOLaDwzonvF4cJtgFz1JM9tHWpT27Q07Z/sPt5TNmxglPGnfBr4WcOkZOA/taxl0z98EXkeBTOG+87pjzPZ2DvXZDzyxP5+ra2zVSEUTBf3JB3N4zQfkqSpM3f1MdJckUYgl88TJU5JPxXh64JuPsN4z0VSSs6XRdvt9XE3gmHxd3J/dLybcJB76Md1wzO2MkMi5L38u3BOI1ZL4+Pp/C/SJ+lM64m02uxFqa7WJswo+oZYsGxD4XFGITOY5j2cYJt3IVpFIZuPyaaFmpozwbWFKhp1IG9iQx+NYRci5UEsNS5dmEH8/MTB1b9iYYKtLcRGoD+bQ8y6eTw0DOXeCOyuu+llLIOYi9mA49PRtZ0sJvZH3Cy7XvmUXU1Reml6wD8I2JHCF0xznW1tT3yAtW4tWVfa3ABhozv8wN6inG9qmRRb3B9QfrZ1HX4S6vZR/kCk2OPIk8Ueu19zPx/po7xzksf/F8MPnjMT5qMgr+WAZI7MaNPH7TBbPrvNORXW7nkSdzU8hp0KUKKz6MmSyuGqKNPZYHA1XGtip+s3kRGTavT9Ssxgrx4JnADdn+Sb/OIYfnWFN58F0P95Oh6eSzSV98NOzNbGKrj1Y/fzKdTWxzInJUItuZE3t9vvK7+ioWxIKom9jo6r1YM1dBV09ilPSwIgq4z4M2JpB3jkb2WvgR9yviGRfXrnEeuj4dKOqBKxYToGNXcnh/sHgLmNYq0t6nipzEjcRqxTL4wbwTv6wZP57AJwSNywHE8uRNu23Ch64Zx83CMm0ys/kKzutymNaVrojVTvvRBvZvg5/MxeBfrXdWl2QuLvIF6MvC3arkGhfvD3+ug47WH2j1lZj94bgsnumWUZ6uvxo2EvAuI9/d1H4BfGxLGoIeEtRLItemA4h3wx7tNB1qVBN3Qd8LcTl0N6uoK6dMl5n2E6gBAcwPjB/nw9WaCNobQa3AjxxlNe5k/RJ08R9Q/9ehJs+gPuzGdOHuah7rCOK0kQ69wPvrLJehfkBugC/nzh1GchUrcg159+JLF7xJgZfkfkPT0JMoi7OwkbdgW/dUD6G+lAH0BFhbQHwBD4oc64/4C0asBzJ3OviaF9XTZX3a1QHsOgvIud5gd58ZjVTuA55e9RPilnF10LZrmmbJeaQx7f4o3r6umEZOLRlyMXiOhB70EoR+0B8cuTjcG9MZ5CARatYX5QQleZx+pdOuDLrb47C6zkbPNYV5FdG4OU7Xe3uv6fyf5+LU7yI+zvloDfFiHPT+8nl5xvjF8zrbxaLGf502JusHRfx8yic8j5bnnD72K9zXQU82GfBbBpa8hr6ijgQ1O+9/5GQKOeTvNeJ30F/WNy99QcwCC9q/C/vJsw57/JZK7/vjK3WWZG/3Qs6d2kughxqA/j95vAO1YPxoOLJqquJk0lcnVt+ZDN71NdCnVUGzPwc7oUcal56QABejUu+OS3+C+XEasxg/7HOoXNrIYo249rscYDEoQ22B/gGpvQiJCdTuF8zWFHoJ0UBTLLmKUtmxs/UiFtQC3qdgQz5+PtvXoc+D3mlX91lfRzRcgqZtg4nPHbml2XGtuywW8vlg1xvUq32Pz8+g/sJ+YshdiNVX/86MSuzc39z89//Qeti9fnp99+v9H5l+MvdnJv5yXPBTh/3u/P2wbPu97f33ts+5+nTmnD1Vv97/EwF6iSs=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


















































































































                                                                                                                                                                                                                     $________;
